security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'


oauth2-providers:
  google:
    path: /login/google
    email-field: emails[0]['value']
    client:
      clientId: 618957030372-7qnv8kll64lr34v37osgcc058falaio4.apps.googleusercontent.com
      clientSecret: s8Soa_T7s3jhJshLKih-hnQJ
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      clientAuthenticationScheme: query
      scope: email
    resource:
      userInfoUri: https://www.googleapis.com/plus/v1/people/me
      preferTokenInfo: false

  facebook:
    path: /login/facebook
    client:
      clientId: 233668646673605
      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: email
    resource:
      userInfoUri: https://graph.facebook.com/me?fields=name,email

spring:
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.springframework.security: DEBUG