MERGE INTO FLIGHT_TBL (FLIGHT_ID, ORIGIN, DESTINATION, DEPARTURE) KEY (FLIGHT_ID) VALUES (1, 'CDG', 'JFK', current_time + 1);
MERGE INTO FLIGHT_TBL (FLIGHT_ID, ORIGIN, DESTINATION, DEPARTURE) KEY (FLIGHT_ID) VALUES (2, 'DME', 'PRG', current_time + 2);
MERGE INTO FLIGHT_TBL (FLIGHT_ID, ORIGIN, DESTINATION, DEPARTURE) KEY (FLIGHT_ID) VALUES (3, 'ZRH', 'BCN', current_time + 3);