CREATE SEQUENCE IF NOT EXISTS FLIGHT_SEQ START WITH 1000;
CREATE SEQUENCE IF NOT EXISTS USER_SEQ START WITH 1000;
CREATE SEQUENCE IF NOT EXISTS RESERVATION START WITH 1000;

CREATE CACHED TABLE IF NOT EXISTS FLIGHT_TBL (
  FLIGHT_ID BIGINT DEFAULT (NEXT VALUE FOR FLIGHT_SEQ) NOT NULL NULL_TO_DEFAULT SEQUENCE FLIGHT_SEQ PRIMARY KEY,
  ORIGIN VARCHAR(255),
  DESTINATION VARCHAR(255),
  ARRIVAL DATETIME,
  DEPARTURE DATETIME,
  FLIGHT_NUMBER VARCHAR(255),
  VERSION TIMESTAMP
);

CREATE CACHED TABLE IF NOT EXISTS USER_TBL (
  USER_ID BIGINT DEFAULT (NEXT VALUE FOR USER_SEQ) NOT NULL NULL_TO_DEFAULT SEQUENCE USER_SEQ PRIMARY KEY,
  EMAIL VARCHAR(255) NOT NULL,
  NAME VARCHAR(255),
);

CREATE CACHED TABLE IF NOT EXISTS RESERVATION_TBL (
  RESERVATION_ID BIGINT DEFAULT (NEXT VALUE FOR RESERVATION_SEQ) NOT NULL NULL_TO_DEFAULT SEQUENCE RESERVATION_SEQ PRIMARY KEY,
  FLIGHT_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
);
