spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/air-tickets
    username: sa
    password:

  mail:
    host: smtp.gmail.com
    username:
    password:
    port: 587
    properties:
      mail.smtp.starttls.enable: true
